name: qictok_mobile
description: A premier TikTok clone for QicTok Pro.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.7
  dio: ^5.4.1
  provider: ^6.1.2
  video_player: ^2.8.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  google_fonts: ^6.2.1
  glassmorphism: ^3.0.0
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
